spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/user_authenticated
    username: user
    password:
    driverClassName: org.h2.Driver

# Name
  application:
    name: user_authenticated

server:
  servlet:
    context-path: /api

app:
  version: '@project.version@'

credentials:
  admin: admin@test.com
  user: user@test.com
  password: 123